name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout

    - name: Set up Ruby
      uses: ruby/setup-ruby
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build

    - name: Upload Artifact
      uses: actions/upload-pages-artifact
      with:
          path: "./_site"

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages
